# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

language: generic

os: osx

osx_image: xcode9.3beta

before_install: mkdir ~/.cider && cd ~/.cider

script:
  - ./scripts/bootstrap.sh
  - ./scripts/test.bats

sudo: required
