workflows:
  new-macos-setup:
    name: Tests
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: edge
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: experiment
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - name: Clean up home directory
        script: |
          brew uninstall --ignore-dependencies $(brew list --formula)
          mv ~/.gitconfig ~/.gitconfig.bak
          cat ~/.gitconfig.bak
      - name: Install
        script: scripts/install.sh
      - name: Test
        script: bats scripts/test.bats
