tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Password manager that keeps all passwords secure behind one password
cask "1password"

# Application launcher and productivity software
cask "alfred"

# Client for the Dropbox cloud storage service
cask "dropbox"

# Bash Automated Testing System
brew "bats-core"

# Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-mononoki-nerd-font"
cask "font-ubuntu-mono-nerd-font"

# Distributed revision control system
brew "git"

# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"

# Lightweight and flexible command-line JSON processor
brew "jq"

# Keep your Mac's application settings in sync
brew "mackup"

# Mac App Store command-line interface
brew "mas"

# Terminal multiplexer with VT100/ANSI terminal emulation
brew "screen"

# Vi 'workalike' with many additional features
brew "vim"

# Internet file retriever
brew "wget"

# UNIX shell (command interpreter)
brew "zsh"

# GPU-based terminal emulator
cask "kitty"
