return {
  {
    "LazyVim/LazyVim",
    opts = {
      icons = {
        diagnostics = {
          Hint = " ",
          Error = " ",
          Warn = " ",
          Info = " ",
          Debug = " ",
          Trace = " ",
        },
        dap = {
          Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
          Breakpoint = " ",
          BreakpointCondition = " ",
          BreakpointRejected = { " ", "DiagnosticError" },
          LogPoint = ".>",
          pause = " ",
          play = " ",
          step_into = " ",
          step_over = " ",
          step_out = " ",
          step_back = " ",
          run_last = " ",
          terminate = " ",
        },
        git = {
          added = " ",
          removed = " ",
          modified = " ",
        },
        misc = {
          collapsed = " ",
          expanded = " ",
          current = " ",
          folder_empty = "",
          folder_closed = "",
          folder_open = "",
          file = "",
        },
        test = {
          pass = "﫟",
          fail = " ",
        },
        kinds = {
          Array = " ",
          Boolean = " ",
          Class = " ",
          Color = " ",
          Constant = " ",
          Constructor = " ",
          Copilot = " ",
          Enum = " ",
          EnumMember = " ",
          Event = " ",
          Field = " ",
          File = " ",
          Folder = " ",
          Function = " ",
          Interface = " ",
          Key = " ",
          Keyword = " ",
          Method = " ",
          Module = " ",
          Namespace = " ",
          Null = " ",
          Number = " ",
          Object = " ",
          Operator = " ",
          Package = " ",
          Property = " ",
          Reference = " ",
          Snippet = " ",
          String = " ",
          Struct = " ",
          Text = " ",
          TypeParameter = " ",
          Unit = " ",
          Value = " ",
          Variable = " ",
        },
      },
    },
  },
}
