# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Mouse lazily follows any focus (window or workspace)
on-focus-changed = ['move-mouse window-lazy-center']

accordion-padding = 280

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

[mode.service.binding]
esc = ['reload-config', 'mode main']

r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

[mode.main.binding]
alt-shift-semicolon = 'mode service'

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

alt-shift-slash = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'

ctrl-alt-shift-h = 'focus left --ignore-floating'
ctrl-alt-shift-j = 'focus down --ignore-floating'
ctrl-alt-shift-k = 'focus up --ignore-floating'
ctrl-alt-shift-l = 'focus right --ignore-floating'

ctrl-alt-shift-cmd-h = 'move left'
ctrl-alt-shift-cmd-j = 'move down'
ctrl-alt-shift-cmd-k = 'move up'
ctrl-alt-shift-cmd-l = 'move right'

ctrl-alt-shift-cmd-0 = 'resize smart -75'
ctrl-alt-shift-cmd-minus = 'resize smart +75'

ctrl-alt-shift-y = 'focus-monitor --wrap-around next'
ctrl-alt-shift-u = 'fullscreen'
ctrl-alt-shift-i = 'workspace-back-and-forth'
ctrl-alt-shift-o = 'move-workspace-to-monitor --wrap-around next'

alt-equal = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

ctrl-cmd-equal = 'move-node-to-workspace 0'
ctrl-cmd-1 = 'move-node-to-workspace 1'
ctrl-cmd-2 = 'move-node-to-workspace 2'
ctrl-cmd-3 = 'move-node-to-workspace 3'
ctrl-cmd-4 = 'move-node-to-workspace 4'
ctrl-cmd-5 = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
if.window-title-regex-substring = 'Terminal Visor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.during-aerospace-startup = true
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.during-aerospace-startup = true
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.during-aerospace-startup = true
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.during-aerospace-startup = true
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 2'

