# Command history database, to track exit statuses & path context
[".config/zsh/zsh-histdb"]
type = "git-repo"
url = "https://github.com/larkery/zsh-histdb"

# Vim colorscheme
[".config/vim/pack/default/start/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/vim"

# Vim status bar
[".config/vim/pack/default/start/vim-airline"]
type = "git-repo"
url = "https://github.com/vim-airline/vim-airline"

# Vim language support 
[".config/vim/pack/default/start/vim-polyglot"]
type = "git-repo"
url = "https://github.com/sheerun/vim-polyglot"


# Tiled scrollable window manager for MacOS. Inspired by PaperWM.
[".hammerspoon/spoons/PaperWM.spoon"]
type = "git-repo"
url = "https://github.com/mogenson/PaperWM.spoon"
