name: dotfiles

on:
  push:
    branches: [ macos-11 ]
  pull_request:
    branches: [ macos-11 ]

  # Allow this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    name: Test new macOS setup
    runs-on: macos-11.0
    env:
      # Have macOS report its version as 10.16
      SYSTEM_VERSION_COMPAT: 1
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_12.3.app

      - name: Clean up home directory
        run: |
          brew remove --force $(brew list --formula)
          mv ~/.gitconfig ~/.gitconfig.bak
          cat ~/.gitconfig.bak

      - name: Place installer
        run: ln -s $GITHUB_WORKSPACE ~/.dotfiles && ls -la ~

      - name: Install 1
        run: helpers/bootstrap.sh

      - name: Install 2
        run: zero setup custom.shared

      - name: Test
        run: helpers/test.bats
