name: Tests

on:
  push:
    branches: [ dev, macos-11 ]
  pull_request:
    branches: [ macos-11 ]

  # Allow this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    name: New macOS setup
    runs-on: macos-11
    env:
      # Have macOS report its version as 10.16
      SYSTEM_VERSION_COMPAT: 1
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Clean up home directory
        run: |
          brew uninstall --ignore-dependencies $(brew list --formula)
          mv ~/.gitconfig ~/.gitconfig.bak
          cat ~/.gitconfig.bak

      - name: Place installer
        run: ln -s $GITHUB_WORKSPACE ~/.dotfiles && ls -la ~

      - name: Install
        run: helpers/bootstrap.sh

      - name: Test
        run: helpers/test.bats
